---
apiVersion: v1
kind: Pod
metadata:
  name: prism-mocktest-deployment
  labels:
    app: prismapimocktest
spec:  
  containers:
    - name: prismapimocktest
      image: sathya20075/prismapitest:5.0
      ports:
        - containerPort: 4010
    - name: prismrunapimocktest
      image: sathya20075/prismnewmanapitest:6.0
      ports:
        - containerPort: 7002
        
  restartPolicy: Always
        
---
apiVersion: v1
kind: Service
metadata:
   name: prismapi-mocktest-service
spec:
   selector:
      app: prismapimocktest
   ports:
      - protocol: TCP
        port: 4011
        targetPort: 4010